class Autogenerated {
  Charecter charecter;

  Autogenerated({this.charecter});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    charecter = json['charecter'] != null
        ? new Charecter.fromJson(json['charecter'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.charecter != null) {
      data['charecter'] = this.charecter.toJson();
    }
    return data;
  }
}

class Charecter {
  int version;
  Info info;
  Klass klass;
  Stats stats;
  Skills skills;
  Weapons weapons;
  Items items;

  Charecter(
      {this.version,
      this.info,
      this.klass,
      this.stats,
      this.skills,
      this.weapons,
      this.items});

  Charecter.fromJson(Map<String, dynamic> json) {
    version = json['version'];
    info = json['info'] != null ? new Info.fromJson(json['info']) : null;
    klass = json['klass'] != null ? new Klass.fromJson(json['klass']) : null;
    stats = json['stats'] != null ? new Stats.fromJson(json['stats']) : null;
    skills =
        json['skills'] != null ? new Skills.fromJson(json['skills']) : null;
    weapons =
        json['weapons'] != null ? new Weapons.fromJson(json['weapons']) : null;
    items = json['items'] != null ? new Items.fromJson(json['items']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['version'] = this.version;
    if (this.info != null) {
      data['info'] = this.info.toJson();
    }
    if (this.klass != null) {
      data['klass'] = this.klass.toJson();
    }
    if (this.stats != null) {
      data['stats'] = this.stats.toJson();
    }
    if (this.skills != null) {
      data['skills'] = this.skills.toJson();
    }
    if (this.weapons != null) {
      data['weapons'] = this.weapons.toJson();
    }
    if (this.items != null) {
      data['items'] = this.items.toJson();
    }
    return data;
  }
}

class Info {
  String name;
  int speed;
  String race;
  String theme;
  String klass;
  int level;
  int xp;
  String description;
  List<String> languages;
  String allignment;
  bool diety;
  int money;

  Info(
      {this.name,
      this.speed,
      this.race,
      this.theme,
      this.klass,
      this.level,
      this.xp,
      this.description,
      this.languages,
      this.allignment,
      this.diety,
      this.money});

  Info.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    speed = json['speed'];
    race = json['race'];
    theme = json['theme'];
    klass = json['klass'];
    level = json['level'];
    xp = json['xp'];
    description = json['description'];
    languages = json['languages'].cast<String>();
    allignment = json['allignment'];
    diety = json['diety'];
    money = json['money'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['speed'] = this.speed;
    data['race'] = this.race;
    data['theme'] = this.theme;
    data['klass'] = this.klass;
    data['level'] = this.level;
    data['xp'] = this.xp;
    data['description'] = this.description;
    data['languages'] = this.languages;
    data['allignment'] = this.allignment;
    data['diety'] = this.diety;
    data['money'] = this.money;
    return data;
  }
}

class Klass {
  int maxHP;
  HistoricMaxHp historicMaxHp;
  int currentHP;
  int eAC;
  int kAC;
  String keyAbility;
  int carryingCap;
  AttackBonus attackBonus;

  Klass(
      {this.maxHP,
      this.historicMaxHp,
      this.currentHP,
      this.eAC,
      this.kAC,
      this.keyAbility,
      this.carryingCap,
      this.attackBonus});

  Klass.fromJson(Map<String, dynamic> json) {
    maxHP = json['maxHP'];
    historicMaxHp = json['historic_max_hp'] != null
        ? new HistoricMaxHp.fromJson(json['historic_max_hp'])
        : null;
    currentHP = json['currentHP'];
    eAC = json['EAC'];
    kAC = json['KAC'];
    keyAbility = json['keyAbility'];
    carryingCap = json['carrying_cap'];
    attackBonus = json['attack_bonus'] != null
        ? new AttackBonus.fromJson(json['attack_bonus'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['maxHP'] = this.maxHP;
    if (this.historicMaxHp != null) {
      data['historic_max_hp'] = this.historicMaxHp.toJson();
    }
    data['currentHP'] = this.currentHP;
    data['EAC'] = this.eAC;
    data['KAC'] = this.kAC;
    data['keyAbility'] = this.keyAbility;
    data['carrying_cap'] = this.carryingCap;
    if (this.attackBonus != null) {
      data['attack_bonus'] = this.attackBonus.toJson();
    }
    return data;
  }
}

class HistoricMaxHp {
  int i1;

  HistoricMaxHp({this.i1});

  HistoricMaxHp.fromJson(Map<String, dynamic> json) {
    i1 = json['1'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['1'] = this.i1;
    return data;
  }
}

class AttackBonus {
  int melee;
  int ranged;
  int thrown;

  AttackBonus({this.melee, this.ranged, this.thrown});

  AttackBonus.fromJson(Map<String, dynamic> json) {
    melee = json['melee'];
    ranged = json['ranged'];
    thrown = json['thrown'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['melee'] = this.melee;
    data['ranged'] = this.ranged;
    data['thrown'] = this.thrown;
    return data;
  }
}

class Stats {
  Strength strength;
  Dexterity dexterity;
  Constitution constitution;
  Intelligence intelligence;
  Wisdom wisdom;
  Charisma charisma;

  Stats(
      {this.strength,
      this.dexterity,
      this.constitution,
      this.intelligence,
      this.wisdom,
      this.charisma});

  Stats.fromJson(Map<String, dynamic> json) {
    strength = json['Strength'] != null
        ? new Strength.fromJson(json['Strength'])
        : null;
    dexterity = json['Dexterity'] != null
        ? new Dexterity.fromJson(json['Dexterity'])
        : null;
    constitution = json['Constitution'] != null
        ? new Constitution.fromJson(json['Constitution'])
        : null;
    intelligence = json['Intelligence'] != null
        ? new Intelligence.fromJson(json['Intelligence'])
        : null;
    wisdom =
        json['Wisdom'] != null ? new Wisdom.fromJson(json['Wisdom']) : null;
    charisma = json['Charisma'] != null
        ? new Charisma.fromJson(json['Charisma'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.strength != null) {
      data['Strength'] = this.strength.toJson();
    }
    if (this.dexterity != null) {
      data['Dexterity'] = this.dexterity.toJson();
    }
    if (this.constitution != null) {
      data['Constitution'] = this.constitution.toJson();
    }
    if (this.intelligence != null) {
      data['Intelligence'] = this.intelligence.toJson();
    }
    if (this.wisdom != null) {
      data['Wisdom'] = this.wisdom.toJson();
    }
    if (this.charisma != null) {
      data['Charisma'] = this.charisma.toJson();
    }
    return data;
  }
}

class Strength {
  int score;
  int saving;

  Strength({this.score, this.saving});

  Strength.fromJson(Map<String, dynamic> json) {
    score = json['score'];
    saving = json['saving'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['score'] = this.score;
    data['saving'] = this.saving;
    return data;
  }
}

class Dexterity {
  int score;
  int saving;

  Dexterity({this.score, this.saving});

  Dexterity.fromJson(Map<String, dynamic> json) {
    score = json['score'];
    saving = json['saving'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['score'] = this.score;
    data['saving'] = this.saving;
    return data;
  }
}

class Constitution {
  int score;
  int saving;

  Constitution({this.score, this.saving});

  Constitution.fromJson(Map<String, dynamic> json) {
    score = json['score'];
    saving = json['saving'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['score'] = this.score;
    data['saving'] = this.saving;
    return data;
  }
}

class Intelligence {
  int score;
  int saving;

  Intelligence({this.score, this.saving});

  Intelligence.fromJson(Map<String, dynamic> json) {
    score = json['score'];
    saving = json['saving'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['score'] = this.score;
    data['saving'] = this.saving;
    return data;
  }
}

class Wisdom {
  int score;
  int saving;

  Wisdom({this.score, this.saving});

  Wisdom.fromJson(Map<String, dynamic> json) {
    score = json['score'];
    saving = json['saving'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['score'] = this.score;
    data['saving'] = this.saving;
    return data;
  }
}

class Charisma {
  int score;
  int saving;

  Charisma({this.score, this.saving});

  Charisma.fromJson(Map<String, dynamic> json) {
    score = json['score'];
    saving = json['saving'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['score'] = this.score;
    data['saving'] = this.saving;
    return data;
  }
}

class Skills {
  int acrobatics;
  int athletics;
  int bluff;
  int computers;
  int culture;
  int diplomacy;
  int disguise;
  int engineering;
  int intimidate;
  int lifeScience;
  int medicine;
  int mysticism;
  int perception;
  int physicalScience;
  int piloting;
  int profession;
  int senseMotive;
  int sleightOfHand;
  int stealth;
  int survival;

  Skills(
      {this.acrobatics,
      this.athletics,
      this.bluff,
      this.computers,
      this.culture,
      this.diplomacy,
      this.disguise,
      this.engineering,
      this.intimidate,
      this.lifeScience,
      this.medicine,
      this.mysticism,
      this.perception,
      this.physicalScience,
      this.piloting,
      this.profession,
      this.senseMotive,
      this.sleightOfHand,
      this.stealth,
      this.survival});

  Skills.fromJson(Map<String, dynamic> json) {
    acrobatics = json['Acrobatics'];
    athletics = json['Athletics'];
    bluff = json['Bluff'];
    computers = json['Computers'];
    culture = json['Culture'];
    diplomacy = json['Diplomacy'];
    disguise = json['Disguise'];
    engineering = json['Engineering'];
    intimidate = json['Intimidate'];
    lifeScience = json['Life_Science'];
    medicine = json['Medicine'];
    mysticism = json['Mysticism'];
    perception = json['Perception'];
    physicalScience = json['Physical_Science'];
    piloting = json['Piloting'];
    profession = json['Profession'];
    senseMotive = json['Sense_Motive'];
    sleightOfHand = json['Sleight_of_Hand'];
    stealth = json['Stealth'];
    survival = json['Survival'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Acrobatics'] = this.acrobatics;
    data['Athletics'] = this.athletics;
    data['Bluff'] = this.bluff;
    data['Computers'] = this.computers;
    data['Culture'] = this.culture;
    data['Diplomacy'] = this.diplomacy;
    data['Disguise'] = this.disguise;
    data['Engineering'] = this.engineering;
    data['Intimidate'] = this.intimidate;
    data['Life_Science'] = this.lifeScience;
    data['Medicine'] = this.medicine;
    data['Mysticism'] = this.mysticism;
    data['Perception'] = this.perception;
    data['Physical_Science'] = this.physicalScience;
    data['Piloting'] = this.piloting;
    data['Profession'] = this.profession;
    data['Sense_Motive'] = this.senseMotive;
    data['Sleight_of_Hand'] = this.sleightOfHand;
    data['Stealth'] = this.stealth;
    data['Survival'] = this.survival;
    return data;
  }
}

class Weapons {
  Weapon weapon;

  Weapons({this.weapon});

  Weapons.fromJson(Map<String, dynamic> json) {
    weapon =
        json['Weapon'] != null ? new Weapon.fromJson(json['Weapon']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.weapon != null) {
      data['Weapon'] = this.weapon.toJson();
    }
    return data;
  }
}

class Weapon {
  String name;
  String damage;
  int attackBonus;
  String damageType;
  String desc;

  Weapon(
      {this.name, this.damage, this.attackBonus, this.damageType, this.desc});

  Weapon.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    damage = json['damage'];
    attackBonus = json['attack_bonus'];
    damageType = json['damage_type'];
    desc = json['desc'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['damage'] = this.damage;
    data['attack_bonus'] = this.attackBonus;
    data['damage_type'] = this.damageType;
    data['desc'] = this.desc;
    return data;
  }
}

class Items {
  Item item;

  Items({this.item});

  Items.fromJson(Map<String, dynamic> json) {
    item = json['item'] != null ? new Item.fromJson(json['item']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.item != null) {
      data['item'] = this.item.toJson();
    }
    return data;
  }
}

class Item {
  String name;
  String description;
  int value;

  Item({this.name, this.description, this.value});

  Item.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    description = json['description'];
    value = json['value'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['description'] = this.description;
    data['value'] = this.value;
    return data;
  }
}
